### ISSUE TITLE
[Question] Remove/override validators

### ISSUE THREAD

**Issue by andra-flowx** [json-editor/json-editor#1172]
### General information

- json-editor version: latest

I know you can add your custom validators, but noticed these don't actually override the existing ones. Is there a way to remove the type validator or override it with a custom implementation? 

P.S. This library rocks!!!

**Comment by germanbisurgi** [comment]
Hello @andra-flowx,

The JSONEditor has core validators  (type, const, maximum, oneOf, etc) that can not be overridden or removed because they follow the JSON schema specification. Custom ones can be added for example when a field validation depends on the value of another field and similar scenarios.

May i ask, what is your goal? JSONEditor has many features that are often overseen that can possibly accomplish what you are looking for.
