### ISSUE TITLE
Generate collection type "map"

### ISSUE THREAD

**Issue by Zakaria59** [json-editor/json-editor#144]
I'm doing tests with this library to find out if it suits my project.
I have java classes quite complex, so I developed a little JsonSchema generator.
I can generate all the types I need except the map.
I need a result like this with the possibility to add key / value:
"map": {
     "value1": {
       "color": "blue",
       "status": "ok"
     }
     "value2": {
       "color": "blue",
       "status": "in_progress"
     }
   }

Any solution? Thanks

**Comment by schmunk42** [comment]
Since map is an object (in JSON) it looks like you'd need to define all possible values - which does not really work, I assume.

There's even no add/delete functionality for object, like there is for arrays. While you can add properties, I think you are looking for adding a (sub-)object with a specific data structure.

Is there something in JSON-schema about that?

**Comment by Zakaria59** [comment]
it's exactly what i want, but this functionality doesn't seem to exist.
I would like to know if there is something planned for that?

**Comment by Zakaria59** [comment]
I don't know the technical constraints but my first idea would be to do something like this:

 "pets": {
      "type": "map",
      "title": "map of pets",
      "key": {
        "type": "string",
      },
      "value": {
        "type": "object",
        "title": "Pet",
        "properties": {
          "kind": {
            "type": "string",
            "enum": [
              "cat",
              "dog",
              "bird",
              "reptile",
              "other"
            ]
          },
          "name": {
            "type": "string"
          }
        }
      }
 }

**Comment by schmunk42** [comment]
Would be great if you could find an example at https://github.com/json-schema-org/json-schema-spec or http://json-schema.org/

**Comment by ToBe998** [comment]
I did a quick check of the json-schema.org website and the issues on it's github page and could not find any information on a "map" or "hash" type of array with named indexes.

Since virtually **every** coding language in existence provides such a data type, i'd call that a bug. In this case, not sticking to the json-schema.org and simply extending it would probably the right approach.

This feature is really important for many use cases.

**Comment by pmk65** [comment]
@ToBe998 You are welcome to create a "map" editor and submit a PR.

**Comment by robocoder** [comment]
Enable the properties button and use a schema like this?
```
{
  "title": "pets",
  "type": "object",
  "patternProperties": {
    "": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "cat",
            "dog",
            "bird",
            "reptile",
            "other"
          ]
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by germanbisurgi** [comment]
I am closing this because i tested @robocoder solution and it works fine. Feel free to reopen
