### ISSUE TITLE
"type": "button" not working

### ISSUE THREAD

**Issue by ariandres** [json-editor/json-editor#1451]
### General information

- json-editor version: last version

```
"button": {
          "type": "button",
          "title": "Button",
          "description": "Button with description and infoText.",
          "options": {
            "infoText": "This field is generated by src/editors/button.js",
            "grid_columns": 6
          }
}
``` 

### Expected behavior
Must render a button

### Actual behavior
Render a text field

### Steps to reproduce the behavior

Direct link to example: https://pmk65.github.io/jedemov2/dist/demo.html

Look in the form tab for the text "Button", this does not render a button

**Comment by ebrensi** [comment]
just noticed this myself.  The bug went away when I reverted to v2.12.

**Comment by schmunk42** [comment]
Likely related to https://github.com/json-editor/json-editor/pull/1442

> Apparently "button" is not a valid type?

It's not in json-schema, so while it breaks BC for json-editor somehow, it also is kindof a [spacebar heating](https://github.com/json-editor/json-editor/pull/1442) "bug".

@ebrensi @germanbisurgi I thought the bug was introduced even earlier, see https://github.com/json-editor/json-editor/issues/1439 - it's in 2.12.0

**Comment by ariandres** [comment]
Thank you very much @ebrensi
The solution worked, I close the issue.
