### ISSUE TITLE
Problem accessing relative references in remote schemas

### ISSUE THREAD

**Issue by hylkevds** [json-editor/json-editor#1582]
### General information

There seems to be an issue with loading remote schemas that use relative reference to other schemas. The entries in the internal `refs` dictionary seem to be complete, but they are not accessed correctly.

- json-editor version: Whatever is currently in the examples below

### Expected behavior

Schema is parsed and an editor is shown

### Actual behavior

Error is given:
reference:'https://raw.githubusercontent.com/opengeospatial/ogcapi-connected-systems/master/swecommon/schemas/json/sweCommon.json#/definitions/AnyComponent' not found!

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsigGb4A22ANCBOWIdDlSyMw5XABMsLLHVTM2WTpnFD86FlBwA3VunqzWHEIXwAPHBOgALVAAZONMghyIopXITATUARk4BjfGxnLCQYWE1cbkgscigAT2D8cj9rJgMFEERLMAB3HBiecgYQGHg6cnw/WAQQTii+DQhAuhxjMyl4AHMoSxxRSsssMX15TlEPCJw5IKiIGNg9NNGQEOFk3D8EFxHDGE34FmpUEGEy/Bz6XiwAVlrwKgArLCqcFnw4sFpj+BFjFjvECksMZUKAACSAwYglAgSxkCAoAD0iIeiAQAFpIcD8AA6ESdRFiCqMKDomwAdkRWOMAGI7qwWAB5RioADa4NELJhcKgEEQSMRFRyOM6YUs6Bo2GSCDoZRxm0IiOiXSwYEQTVgrCVnQCEBg6P28GedDEmLiLmBiERxgt5CpFwVHngVKBNpRaOdiAuAGFeE6caiagBfAC6Qc4PWBWGOVDAYCgLgqEAALHdRABHdAwURiAQJCTMNRQHYZMQwdVvBIZrM5nAIFhxEucLK5Ov8UpNkA/HD4MRl6oEFg4WbzGCLaYZfAPUyoCi6ThlxD4KhSfL9nCB+CdxfL1ebFhvPnRpaGHcryI8OaxMcMCcL8u7kjkCoJXvDE+lh/nnvP959VXkBI5Dbl+q5JC+5iSNIx53isBDfuBf6bBAjYfpwiEJPsFBgGwOBQJAIFLghv75lBLQMn0uS3uk95EWBJGQVILRvC4lE5CWQZBkAA=

```javascript
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "allOf": [
    {
      "$ref": "https://raw.githubusercontent.com/opengeospatial/ogcapi-connected-systems/master/swecommon/schemas/json/sweCommon.json"
    }
  ]
}
```

**Comment by simontaurus** [comment]
I have the same issue - seams like the full path `url#anchor` is used to lookup the document instead of  using `url` for the document and `anchor` within the document.
@schmunk42  / @gbisurgi : I made good experices with preprocessing the schema with https://apitools.dev/json-schema-ref-parser/ - maybe it's a solution to replace the custom code with this lib.

**Comment by germanbisurgi** [comment]
The JSONEditor schema loader is not that advance at the moment. I used apitools.dev/json-schema-ref-parser in the past too for complex schemas like this in the past and worked fine. I will suggest using that package for this scenario.

**Comment by hylkevds** [comment]
Shouldn't this issue then be kept open until the schema loader is updated or replaced?

**Comment by germanbisurgi** [comment]
I closed the issue because updating the schema loader to meet all requirements would take a lot of time. The current version already handles most needs. However, we found an alternative solution for this specific issue that can addresses the problem effectively. If you have suggestions for improvements that can be implemented without major changes, please let me know. Pull requests are always welcome.
