### ISSUE TITLE
Clone Wiki from original repo

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#180]
Suggestion:
Clone the [Wiki ](https://github.com/jdorn/json-editor/wiki) from the original repo, so it can be updated with information regarding the current version. That would help to keep the issues section cleaner.

**Comment by pmk65** [comment]
@schmunk42 I think you just have to turn on the wiki on this repo and then do a pull of the original repo.
Then just move the files to the new wiki repo and commit it.

**Comment by schmunk42** [comment]
Should we continue to use the wiki or just move them to a `docs` folder (or separate repo)?
I often find the wikis on GitHub to be not much recognized by users.

**Comment by pmk65** [comment]
True. But it makes it very easy to move questions/answers etc. from the issue tracker into the Wiki.
And we can just make references to the Wiki in answers. (The README.MD already refers to the (non-existent) Wiki. 🤣  

> The rest of this README contains detailed documentation about every aspect of JSON Editor. For more under-the-hood documentation, check the wiki.

**Comment by schmunk42** [comment]
I've just enabled the Wiki ;)

**Comment by pmk65** [comment]
@schmunk42 I just moved the wiki files from the old repo into the wiki. So I guess we can close this now.

**Comment by niebert** [comment]
The Github-Wiki will be more recognized by users, if you add a link in the README.md and explain, how the users should use it.  Some users of JSONEditor library do not create  a fork and will not dig into the code to improve parts of the sources code. Nevertheless they might have issues for the software design, which can be regarded as major milestone in the software development. So the workflow would be:
* one or more reported issues lead to a wiki page, that discusses the design process for a new major release that covers the issues or improvements.
* the documentation is created before the implementation actually happens. 
* After the design process is aggreed on assignment to specific workpackages are documented in the wiki, ...
* new developers that want contribute to the new release can work through the Wiki document and know where some contributions are missing or contribute directly to wiki because they identified already some design problems, that may be an obstacle for applications of the library in the future
* after a major release is finalized the documentation for the release is ready.

Thank you for integrating the wiki in new repository management. Also some minor contributions like [JSON2Schema](https://niebert.github.io/JSON2Schema), that creates an initial JSON Schema from a given JSON might be helpful in some cases. 

Thank you all for contributing building on Jeremy Dorns work.

**Comment by schmunk42** [comment]
Thank you very much for your input!

btw: Could you point me to the source-code or implementation of JSON2Schema, I didn't find it :)

**Comment by pmk65** [comment]
> 
> 
> Thank you very much for your input!
> 
> btw: Could you point me to the source-code or implementation of JSON2Schema demo, I didn't find it :)

Check the Wiki! 🤣 
When I uploaded Wiki files, I added links to the 2 Schema creators.

https://github.com/niebert/JSON2Schema
