### ISSUE TITLE
What is the best approach to populate enum values from a remote source

### ISSUE THREAD

**Issue by sriks316** [json-editor/json-editor#288]
Hello, I didn't find this in the documenation. Is this it possible to load enum values from a external or different source.
During the time of page load or onlick event, I need to have my enumSource values pulled from a different source.
```

**Comment by pmk65** [comment]
Maybe something like described in #167?

**Comment by VadimTikhonyuk** [comment]
> Maybe something like described in #167?

No

**Comment by VadimTikhonyuk** [comment]
> Hello, I didn't find this in the documenation. Is this it possible to load enum values from a external or different source.
> During the time of page load or onlick event, I need to have my enumSource values pulled from a different source.

![image](https://user-images.githubusercontent.com/13260375/52415390-877a4b80-2aef-11e9-9b7a-3770cd6d651a.png)

and in remote json I have structure like this 
![image](https://user-images.githubusercontent.com/13260375/52415437-9e20a280-2aef-11e9-9400-57918a56b572.png)

But here is problem that you can't hide videos property.

looking for way to do this too

**Comment by pmk65** [comment]
> 
> 
> > Maybe something like described in #167?
> 
> No

If you want to modify the schema properties after generating the form, the ONLY way is to re-parse the schema after modifying (like #167).

Try this [example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AeQK7wAOhcANJDHPAJ5EbDZwD2ARgFZoDG85lO8ABZoAtgybBWzZvADO8AE4BDIgBY+0HArQBHfIm0ATLFADa1NPICMfBJd7AAuhU1wiC5vQVJLJ8Jqo7az9+GECkVHEcAGVFRAgAcyh4eygAM0Q0FGNgFzCw6joouHkFeISNfMDDNDSlfBQHCQAJLJRmKAB1ZgVsuFCoAF88gqCmqH8qgWR0EzhYssSoNAh8EXTMvtyB8KK54FLyyqq4FbWTc0kUJS4Aa1sAd0FkBkcBwf4PiEHgIA&value=ETI=&code=EQKwzgpgJglgLgewE4DoEDsAUByJECGUAntgDQAEAZgK7oDGcMGmAlOQN4A66355A9P3IBlfADcI5OAAtJUCJXzUANnHIBRdNQC25MfmXUIYXnvxJyyAOaad5ALzlw0eMhRg6s7fhQAHJAi+EEiMxihwxnAoEFraANympoLkAMJ4+BHkAEbUcIg86Hz6FlAO5FAIdDoxcBRZZVAodOkR6soQ2jU4OXkY2CwUFo6NAI5GSETCEO0MyDgAxOAYALQuiEjLlMja/QmF2Sj4vkHoUCnSMMpQmI3NBBEAKhAAHnAAcgjyOE9gagBCuXy/RYez4qF85hqH3kKBg6EgIT+CmQEEwWUGKHQLzgwhgWWUcKsINMWRQUAy+EgUUQVis7TKnGAAAZGXE+CTDlAoOoJOg4AAZGC/GLBHB0Al0ADWZCotAYTCwbC4BT4fBkQrJFKp4QQtPpjnVYE1cEpEGpurpknsjmwAEZsOQAPzkbBMh0ALhd9r2pj4yQA4mbyFUkHg+SJPB18OR8KcRCaQvplL6zBYPF5o45nLB1u5I95QariuRfuY4EmytnXKgrGaAGoGIysQsp5IAWU+MEoRCkshL+ejMTsSaMJn2fHTUb8ASCIRgYQiv2isTKmENxtN5r1Vpt9rYzoA2rhoGRsFY8DFT/ijNgALrkT3WWzxbitoQAJQgtaxSAykhkkhbEg2gpl25CYFW6xsJBbjyL8AREM2KYwUM5BYgA7uQ6FwhU6EoAAUsIADybzqDmcwVFUnR8igYzBJM0wQLMSCYIyixgCsazIJs2yMgM7CTt4nqCfgFClomBjCQm5YGAAvsSKrkPJbLkK+6DKey6DAEAA=&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction). When you click the "Test Button", the enum values of the schema will change.  But the form values will remain.

**Comment by stt** [comment]
From my reading of OP question there's no need to change the form once it's rendered ("time of page load") but the values do need to be loaded from remote source. Meaning "watch" isn't necessary, that's for dynamic values.

One option is to take the whole jsonschema definition of the property and move it server side:

    "type": "object",
    "properties": {
      "remotethings": {
        "$ref": "/api/things"
      },

and /api/things would return e.g.

    {
      "title": "Things",
      "type": "string",
      "enum": ["abc","zxc"],
      "options": {
        "enum_titles": ["Abc","Zxc"]
      }
    }

Remote-sourced enums is a usecase I've also needed and having spent many hours stepping through the code it would be nice to have more official examples of the various features.

In addition to above, I'd actually prefer this approach https://github.com/jdorn/json-editor/issues/697#issuecomment-276423283 of loading only enum values instead of json schema from server. Not sure why the following PR wasn't picked up, there's no comments on it.
That linked snippet still works with 1.3.4 if you add it here https://github.com/json-editor/json-editor/blob/6a3941c7db6381e4313faea366a88c03b739ddd5/src/editors/select.js#L160 and also remove "|| Array.isArray(response)" from this check https://github.com/json-editor/json-editor/blob/8d2f0f3d6c3dc327b2dc86b863d748a2d87c3b8b/src/core.js#L416

**Comment by sriks316** [comment]
@pmk65 
i took your example and updated the output value to green:
```

{
  "test1": "Hello World",
  "test": "green"
}
```

But when i click on test button, i still see red as the selected option.

What do I have to do to make green as the selected option since that is the value in the json output/input.

https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AeQK7wAOhcANJDHPAJ5EbDZwD2ARgFZoDG85lO8ABZoAtgybBWzZvADO8AE4BDIgBY%2B0HArQBHfIm0ATLFADa1NPICMfBJd7AAuhU1wiC5vQVJLJ8Jqo7az9%2BGECkVHEcAGVFRAgAcyh4eygAM0Q0FGNgFzCw6joouHkFeISNfMDDNDSlfBQHCQAJLJRmKAB1ZgVsuFCoAF88gqCmqH8qgWR0EzhYssSoNAh8EXTMvtyB8KK54FLyyqq4FbWTc0kUJS4Aa1sAd0FkBkcBwf4PiEHgIA&value=ETI%3D&code=EQKwzgpgJglgLgewE4DoEDsAUByJECGUAntgDQAEAZgK7oDGcMGmAlOQN4A66355A9P3IBlfADcI5OAAtJUCJXzUANnHIBRdNQC25MfmXUIYXnvxJyyAOaad5ALzlw0eMhRg6s7fhQAHJAi%2BEEiMxihwxnAoEFraANympoLkAMJ4%2BBHkAEbUcIg86Hz6FlAO5FAIdDoxcBRZZVAodOkR6soQ2jU4OXkY2CwUFo6NAI5GSETCEO0MyDgAxOAYALQuiEjLlMja%2FQmF2Sj4vkHoUCnSMMpQmI3NBBEAKhAAHnAAcgjyOE9gagBCuXy%2FRYez4qF85hqH3kKBg6EgIT%2BCmQEEwWUGKHQLzgwhgWWUcKsINMWRQUAy%2BEgUUQVis7TKnGAAAZGXE%2BCTDlAoOoJOg4AAZGC%2FGLBHB0Al0ADWZCotAYTCwbC4BT4fBkQrJFKp4QQtPpjnVYE1cEpEGpurpknsjmwAEZsOQAPzkbBMh0ALhd9r2pj4yQA4mbyFUkHg%2BSJPB18OR8KcRCaQvplL6zBYPF5o45nLB1u5I95QariuRfuY4EmytnXKgrGaAGoGIysQsp5IAWU%2BMEoRCkshL%2BejMTsSaMJn2fHTUb8ASCIRgYQiv2isTKmENxtN5r1Vpt9rYzoA2rhoGRsFY8DFT%2FijNgALrkT3WWzxbitoQAJQgtaxSAykhkkhbEg2gpl25CYFW6xsJBbjyL8AREM2KYwUM5BYgA7uQ6FwhU6EoAAUsIADybzqDmcwVFUnR8igYzBJM0wQLMSCYIyixgCsazIJs2yMgM7CTt4nqCfgFClomBjCQm5YGAAvsSKrkPJbLkK%2B6DKcAQA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction

**Comment by pmk65** [comment]
The reason the Output panel doesn't update, is because it listens for changes in the editor fields. And apparently regenerating the form doesn't trigger that. I'll see if I can fix it in a later version.

As for the value, then it DOES update when you click the test button.
Thy this example and switch on the console panel in your browser: https://is.gd/19goBx
It will dump the result of the form once it's ready. Also try clicking the JSON button of the form after you have clicked the test button. It should also show the updated value.

**Comment by pmk65** [comment]
@stt Sounds interesting, but from reading the comments it requires some improvements. Specially the problems with not expanding the $refs fully.
