### ISSUE TITLE
expand_height initially shows 0 height textarea

### ISSUE THREAD

**Issue by jdelfino** [json-editor/json-editor#297]
### Expected behavior
When loading an existing JSON document into the editor, a `format: textarea` field with `expand_height: true` should initially size the textarea to fit the existing text.

### Actual behavior
I see a 0 height text area until I get my cursor into the textarea and move it around. At that point, the textarea sizes itself appropriately.

Before interacting with the text area:
<img width="689" alt="screen shot 2019-02-13 at 11 50 27 am" src="https://user-images.githubusercontent.com/1050141/52728782-ec1d2680-2f85-11e9-8a27-b289780bb091.png">

After: 
<img width="1019" alt="screen shot 2019-02-13 at 11 53 33 am" src="https://user-images.githubusercontent.com/1050141/52728840-02c37d80-2f86-11e9-9061-37ac5c239cdb.png">

### Steps to reproduce the behavior

Relevant schema:
```
    "description": {
      "type": "string",
      "format": "textarea",
      "propertyOrder": 50,
      "options": {
        "expand_height": true
      }
    },
```

Then: 
```
  var editor = new JSONEditor(document.getElementById('editor_holder'), {...});
  editor.on('ready',function() {
      editor.setValue(<json object>);
  });
```

**Comment by pmk65** [comment]
The problem is that no event is fired in JavaScript when you insert content into a textarea by script.
See this fiddle: https://jsfiddle.net/3mq0aLo2/
Only when you press a key or exit the textarea, the event is fired.

But you can trigger the "change" event on the input field from your script, after you have inserted the value. See this [example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AeQK7wAOhcANJDHPAJ5EbDZwD2ARgFZoDG85lO8ABZoAtgybBWzZvADO8AE4BDIgBY+0HArQBHfIm0ATLFADa1NPLgBdCprhEFzegqSWT4TVWCHLXBYhESMwQHvww3rT0JnDyARAA5hoREXAAZswKIkq8jAJoAB7wStpKySk4js5orjS4Cr4KJgCsAAx2FTjOwRCyYV4VcIVEShCGAPrCiAmCudiK+BgDMAC+4VBrmpsrwEA===&value=ETI=&code=EQKwzgpgJglgLgewE4DoEDsAUByJECGUAntgDQAEAZgK7oDGcMGmAlOQN4A6655408ZCkhwAavgA21CJi49e5TsCgQwdJDAAOjDEoBci4JQQJyAI3xIqJ85eumLV4w7vPbTm4/vvvXt389XQI8XEJ9/INDfSPDg6LCAqIiEmMTYpLjk+Oys3Mz8jML04rTS1PKUypyCkorqorKqvIa65tqmmsb69u6utr7O1sGOlpGe/qHR3snx4emxgamJhZnF2aW55fntrd3N/Y3D9eO109Xzlcudg5OL66Ozq72Hu+fbp5vH+/fvr7e/z6vQEfF4gn7/IGg36Q8HA6FggFQiFIJTcXgAXxYAG5uGjyAA3OzQcgAXj4kFgiFQAHMIHAAKKU5A4JAmOAoFRqDTaJjobDYvHQFAwdCaajs2BgTT4OB0AAW9PxEHQcEw6AgAHdyIrlarsPL8OhaWQONgzNQzGYJKpsAY4EhpBR9Ya6BAJPgrRBbVRJJBMQL0NxMVjgEA=&style=ETI=&theme=bootstrap3&iconlib=bootstrap3&object_layout=grid&template=default&show_errors=interaction).

**Comment by jdelfino** [comment]
Thanks for the quick response - will give it a try!
