### ISSUE TITLE
onSubmit method

### ISSUE THREAD

**Issue by mirannda** [json-editor/json-editor#419]
I implemented the onSubmit method, these are the two methods that can be used, what do they think of implementing the project?

```
  onSubmitXHR: function(cmd, url, record) {
    var xhr = new XMLHttpRequest();
    xhr.open("POST", url, true);
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        return JSON.parse(xhr.responseText);
      }
    };
    xhr.send(JSON.stringify({ cmd: cmd, record }));
  },
  onSubmit: function(cmd, url, record) {
    (async () => {
      const rawResponse = await fetch(url, {
        method: "POST",
        credentials: "include",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ cmd: cmd, record })
      }).catch(function(error) {
        console.log("Request failed", error);
      });
      const content = await rawResponse.json();
    })();
  },
```

**Comment by pmk65** [comment]
I have been looking for a way to implement button types into the form. (But it doesn't look like it's possible without breaking the schema standards, due to the way JSON-Editor works)

The simplest solution would be to create a new custom editor, triggered by` "type": "button"` (This is not in the JSON Schema standards) and then configure it using `options`
With the new callback I have implemented in the "2.x" version, it should then be easy to define custom action for the buttons. (A default callback action could be the "onSubmit" method suggested by @mirannda )

**Comment by pmk65** [comment]
**Suggestion for Button editor (for the 2.x release).**

- Triggered by setting `"type": "button"`
- Buttons matches the theme selected.
- Config options is in "options.button" and consist of "**text**", "**action**" and optional "**icon**"
- Callback functions defined under "**window.JSONEditor.defaults.callbacks.button**" (same system as I added in the 2.x version of other editors)
- Buttons leave no trace in the result returned by "getValue()" (editor is not "active")

Example: https://is.gd/SIjpgm

**Comment by mirannda** [comment]
@pmk65, As I see it, perfect, I have tested here and perfect, even can be added the medoto onSubmit with simplicity. Great job, great job!

![image](https://user-images.githubusercontent.com/22716715/61537529-c5b85700-aa0d-11e9-9a52-4eb854036c63.png)

**Comment by pmk65** [comment]
I have added the Button editor to #401 PR now..

**Comment by pmk65** [comment]
Should we close this, as the changes is now available in https://github.com/json-editor/json-editor/tree/develop/2.x
