### ISSUE TITLE
String editor throws error "self.defaults is undefined "

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#494]
### General information

- json-editor version: 2.0 /webpack)

### Expected behavior
No Error
### Actual behavior

> TypeError: self.defaults is undefined  string.js:227:49
    setupCleave string.js:227
    afterInputReady string.js:246
    build string.js:210

### Steps to reproduce the behavior
Run a test example with Cleave enabled,
Direct link to example: https://is.gd/s2jVt8

**Comment by pmk65** [comment]
@sirockin I think something went wrong when you modified the `JSONEditor.defaults` behavior.
Externally defined callback doesn't work any longer either.
https://github.com/json-editor/json-editor/blob/develop/2.x/release-notes.md#jsoneditordefaults

**Comment by pmk65** [comment]
Here's a JavaScript example on how the `callbacks` where defined _pre-Webpack_ (Modifying the global object at runtime):
````javascript
window.JSONEditor.defaults.callbacks.button = {
  "tab1": function(jseditor,e) {
    var idx = 0, obj = jseditor.parent.parent;
    if (obj.format == 'categories') {
      obj.active_tab = obj.rows[idx].tab;
      obj.refreshTabs();
    }
  },
  "tab2": function(jseditor,e) {
    var idx = 1, obj = jseditor.parent.parent;
    if (obj.format == 'categories') {
      obj.active_tab = obj.rows[idx].tab;
      obj.refreshTabs();
    }
  },
  "tab3": function(jseditor,e) {
    var idx = 2, obj = jseditor.parent.parent;
    if (obj.format == 'categories') {
      obj.active_tab = obj.rows[idx].tab;
      obj.refreshTabs();
    }
  },
  "submitform": function(jseditor,e) {
    var res = jseditor.jsoneditor.getValue();
    alert('The result of the form: \n\n' + JSON.stringify(res, null, 2));
  }
};

if (jseditor instanceof window.JSONEditor) jseditor.destroy();
jseditor = new window.JSONEditor(document.querySelector("#json-editor-form"), jedata);
````

**Comment by pmk65** [comment]
We might even need a 3rd parameter. as the 2nd parameter is an object with keys "schema" and optional "startval". So we can just add a "config" key there.

**Comment by pmk65** [comment]
**Suggestions for new data format with replacement config for the old JSONEditor.defaults**

````json


{
   "schema": {},
   "startval": {},
   "config": {
      "options": {
         "theme": "spectre",
         "object_layout": "grid"
      },
      "callbacks": {
         "button": {},
         "ace": {}
      }
   }
}
````
@schmunk42 @sirockin What are your comments on this solution?

**Comment by sirockin** [comment]
Hi @pmk65. Please could you attach files for an e2e test which works with the the old build but doesn't with the new? It will make it easier for me to ensure I've understood and fixed the issue, and also to ensure future PRs don't break this functionality.

**Comment by pmk65** [comment]
See #497 (Couldn't get the test environment up running using the old grunt based setup, but I think it should work)

**Comment by sirockin** [comment]
Thanks for the tests @pmk65 - they seem very well written and clear. The fix for the actual issue was relatively simple - I had already adjusted the AbstractEditor code receive defaults separately but an override of the `init` method in `/src/editors/button.js` meant that for this editor, they weren't being assigned properly.

What is more curious is that I can't get the second test to pass, even though when I reproduce the steps in the test manually, everything works as specified.

**Comment by pmk65** [comment]
Could it be that the 2nd test do this:
1) Tests if the button is in disabled state
2) Fill in a text in the textfield, so that form is valid (minLength is set to 2 chars) 
3) Tests if the button is in enabled state
4) Clicks the button and get test output.

Button editor with `"validated": true` is disabled until form validates and is triggered by the "onchange" event.
When you test it manually, you remove focus from the textfield (which then triggers the "onchange" event) But in the automated test, there's maybe no removing focus to trigger the "onchange" event?  

If we insert an extra textfield (not required, and no minLength.) and then after filling in a value in the required textfield, fill in a dummy value in the 2nd textfield. Then the "onchange" event should have been triggered.

**Comment by sirockin** [comment]
> When you test it manually, you remove focus from the textfield (which then triggers the "onchange" event) But in the automated test, there's maybe no removing focus to trigger the "onchange" event

But it worked in the master build so why shouldn't it work here? I also tried your suggestion in the PR (add `I.click('[data-schemapath="root.button1"] button');` to test and that didn't work. 

> Looking at the Info editor code, it now extends AbstractEditor and not ButtonEditor, which is wrong as it will now leave an empty value in the results.

Damn, my mistake. (I'm sure you can imaging how easy it is to do something like this when making repetitive changes to the headers of 100+ files :-D. Now fixed in current PR

>  What are your comments on this solution?
Personally I never liked the way you modified the global instance of JSONEditor.defaults, so I would prefer something like this.

I don't think your solution is necessary to fix this particular issue - that was just an error on my part in understanding how the inheritance mechansim was working. However I agree we should have a careful look at how globals are used in the application as a whole. Perhaps we can raise a separate issue on this?

**Comment by pmk65** [comment]
@sirockin My solution was also a way to get rid of the `JSONEditor.defaults` entirely. As it's really bad practice to modify the original script/object. 
And by putting the "defaults" into the options, we get a more clean system. Also we don't have to care about breaking changes in the 2.x branch. So it's a perfect time to get rid of the "defaults".

**Comment by sirockin** [comment]
I agree now would be a good time to look into it - but can we do it in a separate issue? I think it's a discussion that goes wider than the two of us, and certainly wider than this bug fix.

**Comment by sirockin** [comment]
@pmk65 can we close this one now?
