### ISSUE TITLE
Selenium tests fails in Firefox

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#563]
### General information

Selenium tests fails in Firefox when using the custom CodeceptJS function `pressKey` function.
This used to work before so something have been changed in the test setup.
(I tested this by restarting the test on #551, which already passed the test. And after restart both the Firefox tests failed)

### Expected behavior

Test should pass in both Selenium Chrome and Firefox tests.

### Actual behavior

Tests fail in Firefox.

### Steps to reproduce the behavior

Restart test on a PR that have already passed the test or upload a dummy PR

**Comment by pmk65** [comment]
@schmunk42 I tried rewriting both helpers and tests without success. 😢 
Maybe for now we should disable the Firefox tests?

**Comment by schmunk42** [comment]
Looks stange, indeed.

Here it fails with a puppeteer error: https://travis-ci.org/json-editor/json-editor/jobs/598525839#L232

```
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer-firefox@0.5.0 install script.
```

**Comment by schmunk42** [comment]
Aren't the error mostly different from each other? In my local tests, I also have issues with FF, but different ones.

These seem like timing issues, since I can 'fix' my local ones with `I.wait()` - but that should not be necessary. It's really painful to have them, since they slow down the tests everytime, would be better to wait for an element.

We might think about having an indicator to show if the form is completely rendered.

**Comment by pmk65** [comment]
CodeceptJS supports `async` and `await`. So if a function is defined with `async`, everything will run asynchronously. Except if a command is prefixed with `await`, then it will wait for this to complete.

The custom `pressKey` helper is defined as `async` and waits for the keypress to finish.

I did some testes in the last PR I made, and it looks like it chokes on `I.pressKey('Tab');` when it tries to convert "Tab" to unicode value. See https://github.com/json-editor/json-editor/pull/566#issuecomment-542814265
