### ISSUE TITLE
remove_button_labels option

### ISSUE THREAD

**Issue by germanbisurgi** [json-editor/json-editor#584]
I am working on the option to remove button labels but i want to discuss some points.

- different buttons use same icons like "edit JSON" and "properties". Here it is ease, just using another icon done that but the problem comes with arrays "delete all", and "delete last". Any idea how i can solve that? and do we need delete last?

- want to change delete icon from "X" to "trash can"  because its more familiar and the x is most used to close things.

from 
![Bildschirmfoto 2019-10-23 um 10 54 06](https://user-images.githubusercontent.com/13135260/67375833-7ee57a80-f583-11e9-98e2-298da7bbda28.png)

to
![Bildschirmfoto 2019-10-23 um 10 52 36](https://user-images.githubusercontent.com/13135260/67375687-4c3b8200-f583-11e9-8b1a-3e7af49de7ed.png)

from
![Bildschirmfoto 2019-10-23 um 11 00 41](https://user-images.githubusercontent.com/13135260/67376506-88bbad80-f584-11e9-84de-a5756c665fd0.png)

to
![Bildschirmfoto 2019-10-23 um 11 01 32](https://user-images.githubusercontent.com/13135260/67376517-8f4a2500-f584-11e9-8d4e-a81a87b5dfe6.png)

- want to change move up and move down icons for tabs top because it will be better to use horizontal arrows

![Bildschirmfoto 2019-10-23 um 10 58 32](https://user-images.githubusercontent.com/13135260/67376270-22368f80-f584-11e9-9868-a4bb58bd396c.png)

@pmk65 @schmunk42 @sirockin what do you think?

**Comment by pmk65** [comment]
https://github.com/json-editor/json-editor#button-custimization ?

**Comment by schmunk42** [comment]
How about collapse-arrows in front of the title and ie. outlined?

Also button groups (see also corner-roundings) do not seem to match.

**Comment by germanbisurgi** [comment]
@pmk65 Icon libs are ok.  I mean an option to declutter the editor from unwanted labels. and also update the icon placement and logic

**Comment by germanbisurgi** [comment]
@schmunk42 did not understood what you mean with "+ item ,x last item should be (also) at the end of an array."  :/

**Comment by pmk65** [comment]
Personally I think we should reduce the iconlibs to a single iconlib, using a custom fontset generated by [Fontello](http://fontello.com/).
That way we can generate a custom fontset with only the icons we need. And if anyone wants to change them for a special project, they can modify the fontset using Fontello and change the icons.
I proposed that solution a while back, but there was no response so I closed the issue. See https://github.com/json-editor/json-editor/issues/265

**Comment by pmk65** [comment]
> 
> Also button groups (see also corner-roundings) do not seem to match.
> 

I think this is because the buttons is not placed inside the same button group or if an icon hidden, but still present in DOM. (CSS uses `:nth-last-child` or` :nth-last-of-type` to style the last button differently)

**Comment by germanbisurgi** [comment]
@buttons are placed really bad. btn-groups with only one button inside h3.

**Comment by pmk65** [comment]
> 
> 
> buttons are placed really bad. btn-groups with only one button inside h3.
> 
True. I don't like that layout either.

> i like the Fontello idea. It will make the code leaner but, someone could complain :)

In the 2.x.x version we have introduced a lot of major changes, so I don't think a minor change like this would cause much problems.
Also we could provide several different Fontello fontsets to choose from. (You can even make a fontset with color icons)

**Comment by germanbisurgi** [comment]
@pmk65 thanks so much for the test case page. I use it to test how layouts and icons behave in multiple themes. And i found tons of little hidden bugs.

However i need to know wich themes and icons should i omit in the process. I omitted jqueryui and bootstrap2 (both theme and icons). How about foundation?

Work is almost done

**Comment by pmk65** [comment]
@germanbisurgi If we proceed with my Fontello suggestion, we only need 1 (static) iconlib. And we can select characters from different fontsets or create custom icons if needed. (I created a custom font for a project I worked on, where some icons where made by overlaying different chars on top of each other to create multiple display variations.) 

Otherwise I would drop the iconlibs for: Bootstrap 2/3 Glyphicons (Doesn't work for BS4), Foundicons 2 (Latest Foundation uses Fontawsome icons AFIK) and FontAwesome 3, 4 (These just contains less fonts than the latest version)

**Comment by pmk65** [comment]
The Spectre theme I made from scratch (Mostly to get to know the Theme functions)
This is the first theme with the Inline `Style Rules` and Theme `options` have been implemented. (Top of theme file)

The `options` are optional (Only `disable_theme_rules` is required) and can be used to set various options in theme functions, that changes the look of the display. (borders, margin etc.)

The `Style Rules` are sets of selectors/CSS rules that will be included when the theme is used. So instead of adding hardcoded Inline Styles to elements, you just add a classname and define a matching Style Rule.
The styling from the Style Rules can be overridden by adding a standard stylesheet with override styling, so it's easy to change if needed.
Any styling that isn't controlled from the Theme (Like classes applied by plugins) can be adjusted in the `afterInputReady` function. (This is needed for plugins like Select2 and Selectize. See the special Test Cases for those on the Playground)

**Comment by germanbisurgi** [comment]
PR #587

**Comment by germanbisurgi** [comment]
I would propose to add unique class names to editors elements instead of having complex css selectors in the future. That will make easier to make css rules.

**Comment by pmk65** [comment]
> 
> 
> I would propose to add unique class names to editors elements instead of having complex css selectors in the future. That will make easier to make css rules.

Problem is that classnames is defined/applied in the themes, So all themes have to apply the same classnames. Otherwise we would have to place some of the rendering logic in the editors.

**Comment by pmk65** [comment]
@germanbisurgi Can we close this?

**Comment by germanbisurgi** [comment]
yes
