### ISSUE TITLE
2.x Theme issues

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#594]
This thread is for discussions about limitations/issues with the current theme implementation in 2.x

- Do we need to extend current theme functions or add new ones to cover all theme features?
- Do we need to refactor some editors?
- etc.

**Comment by pmk65** [comment]
Add list of theme options for all themes that support it (Bootstrap4, Spectre & Tailwind) to documentation. (Same format as in #581 )

**Comment by stroebjo** [comment]
__Checkboxes + compact view__
`getMultiCheckboxHolder()` has no `compact` Parameter like `getFormRadioControl()`, so I can't really distinguish on when to use the compact (horizontal) view and when not.

__More flexible panel layout__
I found the panel layouts a bit limiting. For TWBS4 I thought about using the card component, but I coudn't quite get it working after adding additional div-layers.

__for/id Attributes__
I added `for`/`id` attributes to select the input by clicking on the label (89b3652 - feels a bit hacky ;)). But this doesn't seem to catch `[type=checkbox|file]`? In combination with the custom forms of Bootstrap this is a problem, since the checkbox ist not otherwise selectable than clicking on the label. Maybe this can be done in the core? Would also benefit all themes then.

__Top-Tabs first pane not initially visible in new TWBS4 theme__
Regarding the tabs I'm a bit confused. This doesn't happen in the Bootstrap 4 Example ("Array with format: tabs-top"), but also happens for "Object w. format: categories". I looked at the tab rendering in `editors/object.js` - but that was a bit too much…

When I look in the row parameter in markTabActive(row) I noticed that for the initial rendering the `row.rowPane` div is empty, so I suppose it's redrawn somehow and by that removing the active class?
I add added some div wrappers for the TWBS card display, but updated `getTopTabContentHolder()` correspondingly, so I think it should work (and it does for any click after the initial render ;))

---

Open issues discussed in the TWBS4 Theme v2 PR #588.

**Comment by pmk65** [comment]
> 
> 
> **Checkboxes + compact view**
> `getMultiCheckboxHolder()` has no `compact` Parameter like `getFormRadioControl()`, so I can't really distinguish on when to use the compact (horizontal) view and when not.
> 
I'll start refactoring the multiselect editor and add functions similar to the ones I added for rendering Radio elements. This should solve the checkbox problems.
 
> **More flexible panel layout**
> I found the panel layouts a bit limiting. For TWBS4 I thought about using the card component, but I coudn't quite get it working after adding additional div-layers.
>

Do you have any ideas for improving this?

> **for/id Attributes**
> I added `for`/`id` attributes to select the input by clicking on the label ([89b3652](https://github.com/json-editor/json-editor/commit/89b36526634f93ca788b15286d8b4a39f4b247dc) - feels a bit hacky ;)). But this doesn't seem to catch `[type=checkbox|file]`? In combination with the custom forms of Bootstrap this is a problem, since the checkbox ist not otherwise selectable than clicking on the label. Maybe this can be done in the core? Would also benefit all themes then.
> 

The file editor haven't been refactored so that's why you can't catch the `[type=checkbox|file]` in the current function. Usually you should be able to do it in the `afterInputReady` function, but I don't think the file editor uses that. So we will probably have to refactor the editor.

> **Top-Tabs first pane not initially visible in new TWBS4 theme**
> Regarding the tabs I'm a bit confused. This doesn't happen in the Bootstrap 4 Example ("Array with format: tabs-top"), but also happens for "Object w. format: categories". I looked at the tab rendering in `editors/object.js` - but that was a bit too much…
> 

This is a weird error. I recently fixed a problem in the SimpleMCE editor, where content of the editor wasn't visible until you put focus on the field (Happened when the editor was placed inside a Tabs element) This could be something similar.

> When I look in the row parameter in markTabActive(row) I noticed that for the initial rendering the `row.rowPane` div is empty, so I suppose it's redrawn somehow and by that removing the active class?
> I add added some div wrappers for the TWBS card display, but updated `getTopTabContentHolder()` correspondingly, so I think it should work (and it does for any click after the initial render ;))
> 

From what I can see, the schema is processed in multiple steps. So it makes sense the panels is rendered first.

**Comment by pmk65** [comment]
Looks like we are not the only ones with problems with hidden content.
https://stackoverflow.com/questions/52582990/bootstrap-4-navigation-tabs-content-not-showing-content-on-initial-page-load

**Comment by pmk65** [comment]
@stroebjo I made some modifications to the upload editor #607 which should make it easier to customize.
Currently it uses AStyle Rules set from the editor itself, but those should be moved to the themes. Also if there's need for extra theme functions for upload, we can create/add them now.

**Comment by kameelyan** [comment]
Been using this tool a little while now and here's my general feedback around themeing/styling.

1. There are a number of inline styles getting created that are not in the themes.
2. Inline styles are a violation of most Content Security Policies (unsafe-inline)
3. It would be much better to have .scss files for all styling and have the themes just generate classes/dom structure. This is the approach that I tried to take with my custom theme, but due to point #1 it's near impossible.

**Comment by schmunk42** [comment]
PRs fixing this would be highly welcome.

**Comment by schmunk42** [comment]
I think this has been fixed. Please create new issues if there's still something.
