### ISSUE TITLE
Yes, a long shot...  But... Can you override the color editor?

### ISSUE THREAD

**Issue by Lilwolf** [json-editor/json-editor#621]
### General information

Not a jsoneditor bug, but a cef bug...  java CEF in windows hasn't implemented an implementation of input type="color"...  Ugh...  I just moved from webview to cef to fix a bunch of other issues that were only happening there...  But this might be an impasse...

Can you override what happens when you click a color?  For instance, the spectrum color editor (https://bgrins.github.io/spectrum/) works fine in CEF, at least all their basic examples (<input type='text' id="flat" />) but not the type='color' (under input[type=color] section).

Anyway, was wondering if anyone had seen this problem and if there is any decent way around it.

Thanks! 

Thanks

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by pmk65** [comment]
@Lilwolf The latest build (not the CDN version) now has support for "[Vanilla Picker](https://vanilla-picker.js.org/) - A simple, easy to use vanilla JS color picker with alpha selection" This will be used instead of the default color picker.
There's an example (colorpicker.html) in the `docs/` folder.

**Comment by Lilwolf** [comment]
Are you talking about the latest from the master branch?

Is the only way to change them to change the schema?  I'm wondering if there is a way to change it for all colors by default?

And do I need the alpha version?  Or is it used whenever you use the colorpicker?

            'options': {
                'colorpicker': {
                  'alpha': true
                }
              }?
Thanks!

**Comment by pmk65** [comment]
> 
> 
> Are you talking about the latest from the master branch?
> 
Yes.

> Is the only way to change them to change the schema? I'm wondering if there is a way to change it for all colors by default?
> 
> And do I need the alpha version? Or is it used whenever you use the colorpicker?
> 

You might be able to set the options globally if you set them using `JSONEditor.defaults.options.colorpicker` (I haven't tried) instead of using the schema options.
Both the global and schema options acts as a wrapper for the plugin options. `alpha` is one of those and is not really related to JSON-Editor itself. See https://vanilla-picker.js.org/gen/Picker.html#setOptions__anchor for a list of options for Vanilla picker.

**Comment by Lilwolf** [comment]
Got it working today!  THANKS!  I'm seeing the color as a value (#FFFFFF) instead of the previous current color box in the editor (using Spectre theme).  But the editor itself is working great!  

After getting this working... I found that jcef has problems with drop downs...  but this is officially an cef issue.  

Thanks for your help!
