### ISSUE TITLE
Custom css class support

### ISSUE THREAD

**Issue by gnom7** [json-editor/json-editor#63]
According to the README I can specify my own CSS styles, but I cannot find the way to specify CSS classes for elements in json schema.

> If you want to specify your own styles with CSS, you can use barebones, which includes almost no classes or inline styles.

Can we add something similar to
```
"style": {
      "add": "btn-success"
    }
```
to element meta information in json schema?
Also see https://github.com/jdorn/json-editor/issues/158#issuecomment-389634771

**Comment by pmk65** [comment]
You don't need to apply classes in order to restyle the form. You can use the "data-schemapath" attribute to select the various parts. Example (Look at the bottom of the CSS): https://codepen.io/pmk/pen/KxbNMo
Another option is to create a custom theme. That way you have control over most of the output.

**Comment by pmk65** [comment]
Info added to wiki

**Comment by osmanraifgunes** [comment]
"data-schemapath" will not work for arrays. For example I have five elements under array, and schemepath will be dynamic :

data-schemapath="root.0"
data-schemapath="root.1"
.
.
.
data-schemapath="root.n"

**Comment by germanbisurgi** [comment]
Set a background color on all  elements that have a attribute data-schemapath value that begins with "root.":

```css
[data-schemapath^="root."] {
  background: #ffff00;
}
```
