### ISSUE TITLE
AbstractIconLib not available as property

### ISSUE THREAD

**Issue by kameelyan** [json-editor/json-editor#658]
Similar to #643, working on creating a new theme that's not compiled. The use case here is:

Using a compiled version of the js (dist), I want to apply a new theme and iconlib on the fly.

Currently only AbstractEditor and AbstractTheme are available. Can we get AbstractIconLib as well?

**Comment by schmunk42** [comment]
@germanbisurgi You worked a lot with icons in json-editor. WDYT?

**Comment by germanbisurgi** [comment]
Here is the theme [test](https://github.com/json-editor/json-editor/blob/master/tests/pages/themes.html) 

The editors is always reloaded and passed a new config with different iconLib and theme.

**Comment by kameelyan** [comment]
Hey @germanbisurgi, this doesn't help. This reloads and passes a new config with different iconLib that's already defined. I'm trying to define my own custom iconLib, during runtime. To do so, I'll need to extend the AbastractIconLib, which isn't currently possible as it's not exposed as a property on JSONEditor.

**Comment by germanbisurgi** [comment]
Oh now i understand, sorry. Yeah i did a lot with themes and icons testing but not much the implementation. So much happen since. Reading the code and the readme i found that the abstract theme is exposed like this:

`JSONEditor.AbstractTheme.`

Its a class that can be extended like this:

`var bootstrap4Theme = AbstractTheme.extend({...my stuff...})`

Look at any of the existing classes for [examples](https://github.com/json-editor/json-editor/blob/master/src/themes/bootstrap4.js).

I hope that helps.

**Comment by kameelyan** [comment]
Yep, I'm using that already for my new theme, but AbstractTheme and AbstractIconLib are separate. You define theme and iconlib in separate properties as well. The issue is that AbstractTheme is exposed, but AbstractIconLib isn't, so it's not available to extend off of in real-time.

For reference:
https://github.com/json-editor/json-editor/blob/914a08a07bf6cf09da0eb9337b00ab3b00a66295/src/core.js#L815-L816

**Comment by germanbisurgi** [comment]
Yap i see. it should be exposed too like abstractTheme. I am working on something else right now but my next PR will expose that.

**Comment by germanbisurgi** [comment]
Added here #660 :)
