### ISSUE TITLE
Is it possible to save the json generated data to a local text file?

### ISSUE THREAD

**Issue by DineshBhudia** [json-editor/json-editor#768]
### General information

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by schmunk42** [comment]
Out of scope, you need to implement it on your own.

**Comment by niebert** [comment]
Access to filesystem is not possible for browsers because of security reasons. Use FilesaverJS by Eli Grey for saving files from your browser - see  https://github.com/eligrey/FileSaver.js create a string from the JSON with `stringify` prior to saving:
```javascript 
var myjson = editor.getValue();
var jsonstring = JSON.stringify(myjson, null, 4);
```
Save the string `jsonstring` with FileSaverJS. It just uses the dowload feature of browsers to create a local file, but you are not downloading a remote file, you are downloading data from your browser application (see [AppLSAC](https://en.wikiversity.org/wiki/AppLSAC) for more details.

If you want load files in a Browser with LoadFIle4DOM https://gitlab.com/niehausbert/loadfile4dom  see examples https://niehausbert.gitlab.io/loadfile4dom/
You will get a string. Then you parse the string into a JSON 
```javascript
vJSONstring = this.aLinkParam.getValue(vDataID);
       try {
         myjson = JSON.parse(vJSONstring);
       } catch (e) {
         console.error("ERROR JSON  Syntax: "+e);
         mjson = null;
       }
       if (vJSON) {
         console.log("myjson successfully parsed:\n"+JSON.stringify(myjson,null,4));
       }
```
