### ISSUE TITLE
How to Add dateFormat in Flatpickr Used by JsonEditor

### ISSUE THREAD

**Issue by orenjisland** [json-editor/json-editor#958]
### General information
We are using the JSONEditor. And we have another JS file that overwrites some of its functionalities. One feature that we are trying to modify is the datetime feature of JSONEditor which uses the Flatpickr. We are trying to set a dateFormat for the Flatpickr but cannot modify it on the build() part of dateTime.

- json-editor version: 1.3.5

### Expected behavior
Input type="date" field must have a placeholder and format date in "YYYY-MM-DD" instead of native format per browser (example: "DD/MM/YYYY" in Chrome)

### Actual behavior
Tried using the Flatpickr in another code and the dateFormat of "YYYY-MM-DD" is applied. But in my code, when I do the extend to JSONEditor datetime, the dateFormat I set in the Flatpickr does not reflect.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
var oldDateTimeEditor = JSONEditor.defaults.editors.datetime;
  JSONEditor.defaults.editors.datetime = oldDateTimeEditor.extend({
    build: function () {
      this._super();

      if (!this.input) return;
      this.input.setAttribute("placeholder", 'YYYY-MM-DD');

      this.options.flatpickr = {
        dateFormat: 'Y-m-d'
      };
    }
  });
```

This is the HTML once schema has been loaded and my modified code for JSONEditor dateTime has been run.
```
<input type="date" class="form-control" pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}$" data-schemaformat="date" placeholder="YYYY/MM/DD" name="root[Attributes][ExpiryDate]">
````

This is still the output of the dateTime field
![image](https://user-images.githubusercontent.com/82487028/114648150-ec094480-9d10-11eb-9ffb-257737d5ef10.png)

**Comment by lebaphi** [comment]
Hi @orenjisland, I faced the same issue, did you fix that?

**Comment by eduo** [comment]
@orenjisland  @lebaphi  Hello! How did you solve this?

**Comment by Pirgosth** [comment]
Hi ! I was having the same issue, and after a lot of struggle it was because I forgot to link Flatpickr in my html file !
I think that was the issue OP was having as well, because you can see the vanilla datepicker on his screenshot.

You can link the CDN of Flatpickr here: [https://flatpickr.js.org/getting-started](https://flatpickr.js.org/getting-started)

 To now if it works, it should look like that:
![image](https://github.com/json-editor/json-editor/assets/22637850/45a3b0ac-220a-44a4-a1eb-cb1baa9e2276)
